### ISSUE TITLE
Develop test for multiple burned cells on first day

### ISSUE THREAD

**Issue by mbjoseph** [StumWhere/Proximal-Segmenter#3]
We want to make sure that if we have multiple pixels burned on the same (first) day that are spatially separate, we get multiple events. We need a second test to ensure that if these pixels are adjacent, we still get one.

**Comment by StumWhere** [comment]
Good catch. Luckily it was a simple fix. Instead of adding one to just the 'first' fire object ID, it now adds one to all pixels with a label on the first day. Added more pixels that 'burned' on day of the dummy data set, to test this.
